### ISSUE TITLE
Regular update form fails

### ISSUE THREAD

**Issue by Sprachprofi** [olegantonyan/translateable#10]
I am using a regular form, not a nested fields one. If the form is returned as invalid, the fields contain JsonB code rather than appropriate language content:

![image](https://user-images.githubusercontent.com/801116/28384592-8db853fa-6cc5-11e7-891b-3ce9605dbec9.png)

**Comment by olegantonyan** [comment]
Let me check this in the next few days. I think I know why this is happening

**Comment by olegantonyan** [comment]
Proper fix is tricky since Rails uses `_before_type_cast` to retrieve field's value in this particular case (https://github.com/rails/rails/blob/master/actionview/lib/action_view/helpers/tags/base.rb#L51). I don't know how to do this without hacking Rails internals (which is bad idea).

But there is a workaround:
```
<%= form.text_field :text, value: model.text %>
```
Pass translateable field as a value explicitly. In this case it will bypass `_before_type_cast`

**Comment by Sprachprofi** [comment]
That solves it and is not too much of a hassle, thanks!
